sudo: false
language: python
os:
  - linux
dist: trusty
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master
    - develop
install:
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install cython
  - pip install numpy
  - pip install tifffile coveralls pytest-cov
  - python setup.py build_ext --inplace --cov
script: py.test --cov pytiff
after_success: coveralls
