language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtiff
install:
  - pip install cython numpy tifffile
  - pip install -e .
script: py.test test
branches:
  only:
    - master
    - develop
