language: python
os:
  - linux
dist: trusty
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master
    - develop
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo apt-get install -y libtiff5 libtiff5-dev
  - gcc --version
install:
  - pip install --upgrade pip
  - pip install --upgrade pytest hypothesis
  - pip install cython
  - pip install numpy
  - pip install scikit-image
  - pip install tifffile coveralls pytest-cov
  - python setup.py build_ext --inplace
script: py.test .
