language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.5"
install:
  - pip install cython numpy tifffile
  - pip install -e .
script: py.test test
branches:
  only:
    - master
    - develop
